const IMG={restaurant:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=82',coffee:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=82',dessert:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1000&q=82',ramen:'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1000&q=82',sushi:'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1000&q=82',steak:'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=82',japan:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1000&q=82',garden:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1000&q=82',ocean:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=82',city:'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1000&q=82'};
const days=[
{n:1,date:'27/9（日）',title:'抵達福岡',sub:'香港／台北會合 → 天神入住',events:[['17:00','6人從香港出發，抵達福岡機場','航班 UO638'],['18:00','2人從台北出發，抵達福岡機場，8人會合',''],['18:30','的士前往天神市區酒店','機場往天神約20–30分鐘；毋須租車'],['19:30','天神晚餐選擇','博多もつ鍋前田屋／水たき長野'],['住宿','Richmond Hotel Tenjin Nishidori','第1晚']]},
{n:2,date:'28/9（一）',title:'天神早午餐＋LaLaport＋GUNDAM',sub:'自由活動 → 購物 → 夜間投影表演',events:[['早上','自由活動','酒店周邊悠閒散步、補眠或自行購物'],['12:30','天神早午餐','NOOICE tenjin／いくら博多店／manu coffee 大名店'],['14:30','的士前往 LaLaport 福岡','福岡市博多区那珂6-23-1；約20–25分鐘'],['15:00–17:30','LaLaport購物＋GUNDAM BASE FUKUOKA','約25米高 RX-93ff ν鋼彈立像'],['17:30–18:00','商場內咖啡店歇息','自由安排'],['18:00–19:00','自由活動','購物／GUNDAM PARK拍照'],['19:00–19:30','GUNDAM夜間投影燈光表演','建議提前15分鐘到場'],['20:00','的士返回天神','約20–25分鐘'],['20:30','天神晚餐','任選餐廳'],['住宿','Richmond Hotel Tenjin Nishidori','第2晚']]},
{n:3,date:'29/9（二）',title:'福岡 → 鹿兒島中央 → 霧島溫泉',sub:'九州新幹線 → 租車 → 酒店會席',events:[['11:00','酒店退房',''],['11:00–13:00','天神早午餐＋自由活動','やりうどん福岡店'],['13:15','抵達博多站，搭九州新幹線','さくら753号'],['14:01–15:42','博多 → 鹿児島中央','約100分鐘'],['15:45','辦理租車','建議2部7–8人座廂型車'],['16:30','出發霧島観光ホテル','約60分鐘'],['17:30','入住霧島観光ホテル','溫泉放鬆'],['19:00','酒店內會席料理晚餐',''],['住宿','霧島観光ホテル（AUBEGIO）','1晚']]},
{n:4,date:'30/9（三）',title:'霧島神話之里＋霧島神宮＋仙巖園',sub:'展望台 → 神宮 → 錦江灣庭園',events:[['早上','酒店早餐，慢慢收拾行李',''],['11:00','酒店退房',''],['11:30–12:30','霧島神話之里公園','觀光纜車、展望台'],['12:45','霧島神宮參拜','鹿児島県霧島市霧島田口2608-5'],['13:15','前往仙巖園','約1小時'],['14:15–16:00','仙巖園＋園內午餐','櫻島、錦江灣、庭園、貓神社、薩摩切子'],['16:30','入住鹿兒島中央站西口酒店',''],['20:00','晚餐選擇','みやま本舗／焼肉なべしま'],['住宿','東横INN鹿児島中央駅西口','第1/4晚']]},
{n:5,date:'1/10（四）',title:'櫻島自駕一日遊',sub:'渡輪帶車 → 火山展望 → 足湯',events:[['10:30','自駕前往櫻島渡輪碼頭','約15分鐘'],['11:00','櫻島渡輪','可連人帶車上船，約15分鐘'],['11:30–12:00','櫻島遊客中心','火山地質與噴發歷史'],['12:15–13:00','湯之平展望台','免費停車'],['13:15–14:15','櫻島午餐','櫻島市場食堂／お食事処海月'],['14:30–15:15','有村熔岩展望所','觀賞熔岩地貌'],['15:30–16:15','長腳湯（足湯）','免費足湯休息'],['16:45','渡輪返回鹿兒島',''],['19:00','晚餐選擇','鹿兒島屋台村／めっけもん／新港食堂'],['住宿','東横INN鹿児島中央駅西口','第2/4晚']]},
{n:6,date:'2/10（五）',title:'南薩摩：知覽・Cafe Cochi＋指宿砂浴',sub:'武家屋敷 → 古民家午餐 → 砂蒸溫泉',events:[['10:30','出發前往知覽','約1小時'],['11:30–12:30','知覽武家屋敷庭園','門票大人¥530'],['12:30–14:00','Café Cochi 午餐','百年古民家洋食、和牛牛筋咖哩'],['14:15','前往指宿','約30分鐘'],['15:00–16:30','砂むし會館 砂樂','砂樂套裝約¥2,100'],['16:45','池田湖／開聞岳遠望（二選一）','視體力可略過'],['19:30','晚餐選擇','大衆酒場かどや／とりくら／豚とろ'],['住宿','東横INN鹿児島中央駅西口','第3/4晚']]},
{n:7,date:'3/10（六）',title:'精品咖啡＋平川動物公園＋天文館',sub:'輕鬆上午 → 動物園 → 白熊刨冰 → 採購',events:[['10:30','精品咖啡','danken COFFEE／可否三昧／Voila Coffee／くじらcafé'],['12:00–13:00','午餐','うなぎの末よし'],['13:30–16:00','平川動物公園','樹熊、長頸鹿、櫻島景色'],['16:30–18:00','天文館＋白熊刨冰','天文館むじゃき本店'],['18:00','AMU PLAZA／天文館伴手禮',''],['18:45','晚餐選擇','ざぼんラーメン／いちにいさん／Gyudo!'],['21:00','整理行李，準備翌日還車',''],['住宿','東横INN鹿児島中央駅西口','第4/4晚']]},
{n:8,date:'4/10（日）',title:'鹿兒島 → 福岡 → 香港',sub:'還車 → 國內線 → 4人返港',events:[['09:30','酒店退房',''],['10:00–10:40','鹿兒島機場辦理登機','約40分鐘'],['12:00','鹿兒島 → 福岡','國內線約50分鐘'],['13:00','抵達福岡機場','轉乘接駁約10–15分鐘'],['16:15','福岡 → 香港','4人返港；餘下4人福岡自由行'],['晚上','餘下4人福岡自由活動','可check-in、寄存行李'],['住宿','博多西中州 tokyo inn','自行安排']]},
{n:9,date:'4/10–6/10',title:'附加：福岡自行安排',sub:'餘下4人自由行',events:[['4/10 晚上','福岡市內自由活動＋晚餐','築地壽司鮮福岡總本店等'],['5/10','半日遊三選一','太宰府天滿宮／柳川遊船／糸島海邊'],['6/10','最後採購','博多站藥妝、伴手禮；預留退稅及機場交通']]}
];
const restaurants=[
['福岡酒店附近','晚餐','博多もつ鍋 前田屋','博多もつ鍋 前田屋','福岡代表性牛雜鍋；抵達第一晚晚餐候選。','福岡市博多区博多駅前3-23-17｜092-260-7273','restaurant'],
['福岡酒店附近','晚餐','水たき 長野','水たき 長野','清爽系博多水炊き。','福岡市博多区対馬小路1-6｜092-281-2200','japan'],
['福岡酒店附近','早餐／定食','Sabataro','さばたろう','主打鯖魚定食。','1 Chome-5-11 Akasaka, Chuo Ward, Fukuoka 810-0042','japan'],
['福岡天神／大名','購物','上久醬油','ジョーキュウ醤油 小売館','福岡在地醬油與調味品採購點。','1 Chome-12-15 Daimyo, Chuo Ward, Fukuoka 810-0041','japan'],
['福岡天神／大名','咖啡豆','Nishinaya coffee Daimyo','ニシナ屋珈琲 大名1-3-26niR焙煎所','先選豆、再決定烘焙深淺；依你提供的資料約等30分鐘烘焙。','1 Chome-3-26 Daimyo, Chuo Ward, Fukuoka 810-0041','coffee'],
['福岡天神／大名','咖啡','Blue Bottle Coffee Fukuoka Tenjin Cafe','ブルーボトルコーヒー福岡天神カフェ','天神警固神社附近精品咖啡；官方目前列示每日8:00–20:00、室內73席、戶外18席。','天神2-2-20 警固神社社務所ビル1F','coffee','https://store.bluebottlecoffee.jp/pages/fukuoka_tenjin'],
['福岡天神／大名','咖啡','Little Stand Daimyo store','Little Stand 大名店','大名散步途中臨時休息點。','Daimyo 1-3-5 ARKCUBE101, Chuo Ward, Fukuoka 810-0041','coffee'],
['福岡天神／大名','甜品','いちごや cafe TANNAL 福岡大名店','いちごや cafe TANNAL','草莓系甜品；你提供資料標註營業至23:00。','Daimyo 1-3-14 花形館A 1, Chuo Ward, Fukuoka 810-0041','dessert'],
['福岡天神／大名','甜品','RIZ CAFE CREPE RIZ 大名店','クレープ RIZ 大名店','可麗餅甜品選擇。','Daimyo 1-1-16 宮田ビル101, Chuo Ward, Fukuoka 810-0041','dessert'],
['福岡天神／大名','水果派','Qu’il fait bon 福岡','キル フェ ボン福岡','水果派甜點店。','Tenjin 2-4-11 1F, Chuo Ward, Fukuoka 810-0001','dessert'],
['福岡天神／大名','晚餐','Toriboshi Daimyo','とりぼし大名店','雞肉燒肉＋沙瓦類，另有水果系飲品。','Daimyo 1-9-18 越智ビル, Chuo Ward, Fukuoka 810-0041','steak'],
['福岡天神／大名','牛肉飯','Red Rock Hakata Daimyo','レッドロック 博多大名店','牛肉丼選擇。','Daimyo 1-12-26 ビエント今川336 101号, Chuo Ward, Fukuoka 810-0041','steak'],
['福岡天神／大名','炸牛排','元村炸牛排 福岡天神西通店','牛かつもと村 福岡天神西通り店','日式牛かつ。','Daimyo 1-14-5, Chuo Ward, Fukuoka 810-0041','steak'],
['福岡天神／大名','早午餐','NOOICE tenjin','NOOICE','澳式鬆餅、酪梨吐司；Day 2 早午餐選項。','Imaizumi 1-18-3, Chuo Ward, Fukuoka','coffee'],
['福岡天神／大名','早午餐','いくら博多店','いくら博多店','漢堡排蛋包飯；原行程資料註明不接受預約，建議11點前到。','Hakataekimae 2-8-12, Hakata Ward, Fukuoka','restaurant'],
['福岡天神／大名','咖啡甜品','manu coffee 大名店','manu coffee','原行程列為博多咖啡蛋糕選項。','Daimyo 1-1-3, Chuo Ward, Fukuoka','coffee'],
['福岡天神／大名','燒鳥','焼とりの八兵衛 天神店','焼とりの八兵衛','創業40年老字號燒鳥；原行程列Tabelog 3.52。','福岡市天神一帶','steak'],
['福岡天神／大名','晚餐','肉の山翔','肉の山翔','和牛明太子丼、燒肉拼盤。','福岡市天神／大名一帶','steak'],
['福岡LaLaport附近','咖啡豆','Honey Coffee','ハニー珈琲 那珂本店／焙煎工場・配送センター','精品咖啡豆店兼焙煎工場；官方列示可試飲。','Naka 6-1-37, Hakata Ward, Fukuoka 812-0893｜092-292-7668','coffee','https://www.honeycoffee.com/shop'],
['福岡LaLaport附近','咖啡','Starbucks Coffee - LaLaport Fukuoka','スターバックス ららぽーと福岡','就在LaLaport內，購物中途休息。','LaLaport Fukuoka 3F, Naka 6-23-1','coffee'],
['福岡LaLaport附近','餐廳','nikuniku udon LaLaport Fukuoka','肉肉うどん','LaLaport內烏龍麵選擇。','LaLaport Fukuoka, Naka 6-23-1','restaurant'],
['福岡LaLaport附近','餐廳','仙台牛たん 利久 LaLaport Fukuoka','Sendaitanyarikyu','LaLaport內牛舌料理。','LaLaport Fukuoka, Naka 6-23-1','steak'],
['福岡市區／博多','清酒／牡蠣','牡蠣と日本酒 Oyster & Sake','牡蠣と日本酒','牡蠣＋日本酒晚間選擇。','Sumiyoshi 1-6-8 Oak Villa Bureau Sumiyoshi riva 201, Hakata Ward','restaurant'],
['福岡市區／博多','Craft Sake','LIBROM Craft Sake Brewery','リブロム','街中釀造所＋PUB；官方介紹可享用搾りたて craft sake 與麴／酒粕料理，從博多／天神步行約15分鐘。','Takasago 1-21-27 ボンフル高砂103, Chuo Ward, Fukuoka','restaurant','https://librom.jp/'],
['福岡市區／博多','日本酒','百薬「福岡の日本酒専門バー」','百薬','福岡日本酒專門酒吧。','Haruyoshi 3-16-41, Chuo Ward, Fukuoka 810-0003','restaurant'],
['鹿兒島市區','薩摩黑雞','みやま本舗 天文館店','みやま本舗','薩摩黑雞刺身＋熔岩燒；原行程列半個室、Tabelog 3.41。','天文館','steak'],
['鹿兒島市區','燒肉','焼肉なべしま与次郎本店','焼肉なべしま','黑毛和牛燒肉，設沙律吧。','与次郎1-9-53, Kagoshima｜099-255-8929','steak'],
['鹿兒島市區','屋台／酒','鹿兒島屋台村','鹿児島屋台村','18間屋台集中，可試燒酎、啤酒、鄉土料理。','中央町11, Kagoshima','restaurant'],
['鹿兒島市區','迴轉壽司','めっけもん 鹿兒島中央站店','めっけもん','迴轉壽司選擇。','鹿兒島中央站一帶','sushi'],
['鹿兒島市區','海鮮','新港食堂','新港食堂','握壽司、生魚片定食；原行程列市場直送。','鹿兒島市區','sushi'],
['鹿兒島市區','酒場','大衆酒場かどや','大衆酒場かどや','鮪魚刺身及烏冬；原行程列Tabelog 3.25。','千日町13-1, Kagoshima','restaurant'],
['鹿兒島市區','薩摩黑雞','とりくら天文館店','とりくら','本格薩摩黑雞燒鳥；原行程列完全個室、Tabelog 3.64。','天文館','steak'],
['鹿兒島市區','拉麵','豚とろ','豚とろ','濃厚豚骨湯底拉麵。','鹿兒島市區｜099-258-9900','ramen'],
['鹿兒島市區','鰻魚','うなぎの末よし','うなぎの末よし','創業80年鰻魚飯老店，天文館通站步行約5分鐘。','天文館','restaurant'],
['鹿兒島市區','白熊刨冰','天文館むじゃき本店','天文館むじゃき','白熊刨冰創始老店。','千日町5-8, Kagoshima｜099-222-6904','dessert'],
['鹿兒島市區','拉麵','ざぼんラーメン 中央駅店','ざぼんラーメン','鹿兒島本地老字號拉麵。','鹿兒島中央站一帶','ramen'],
['鹿兒島市區','黑豚','いちにいさん Amu Plaza店','いちにいさん','黑豚料理。','AMU PLAZA 鹿兒島','steak'],
['鹿兒島市區','和牛','熟成燒肉 Gyudo! 本店','Gyudo!','鹿兒島黑毛和牛燒肉；原行程標註牧場直營。','天文館通站附近','steak'],
['霧島','會席料理','霧島観光ホテル','AUBEGIO','入住當晚酒店內會席料理＋溫泉。','霧島溫泉一帶','japan'],
['知覽／指宿','古民家洋食','Café Cochi','Café Cochi','百年古民家洋食；原行程指定和牛牛筋咖哩。','知覧町郡93, Minamikyushu｜0993-76-8255｜11:00–17:30','restaurant'],
['櫻島','午餐','櫻島市場食堂','桜島市場食堂','櫻島港附近海鮮／在地料理。','櫻島港附近','sushi'],
['櫻島','午餐','お食事処 海月','お食事処海月','櫻島港附近，可選海鮮丼、生魚片定食。','櫻島港附近','sushi'],
['福岡延伸','深夜壽司','築地壽司鮮 福岡總本店','築地寿司鮮 福岡総本店','4/10晚上的自由活動晚餐備選；原行程資料標註營業至凌晨5點。','春吉3-11-19, Chuo Ward, Fukuoka｜092-718-3611','sushi']
];
const spots=[['福岡酒店附近','天神／大名散步區','第一晚與Day 2上午自由活動、咖啡、購物。','city'],['福岡天神／大名','警固神社','就在Blue Bottle附近，可順路散步。','japan'],['福岡LaLaport附近','LaLaport Fukuoka＋GUNDAM BASE','Day 2核心購物點，晚上有GUNDAM投影。','city'],['鹿兒島市區','天文館通','餐廳、白熊刨冰、伴手禮集中。','city'],['鹿兒島市區','仙巖園','櫻島、錦江灣、庭園、貓神社、薩摩切子。','garden'],['霧島','霧島神宮','原行程安排的神宮參拜。','japan'],['櫻島','湯之平展望台','自駕停留的火山展望點。','ocean'],['知覽／指宿','知覽武家屋敷庭園','傳統武家屋敷與庭園散策。','garden'],['知覽／指宿','砂むし會館 砂樂','指宿天然砂蒸溫泉。','ocean'],['福岡延伸','太宰府／柳川／糸島','5/10三選一。','ocean']];
const img=k=>IMG[k]||IMG.restaurant;
const checklist=['護照（效期 >6月）','旅行保險＋旅遊不便險','實體信用卡 VISA／MASTER＋掛失電話','電子機票收據','現金及日圓零錢','行動電源≤2個','轉換插頭／多孔插座','個人藥品','防曬乳、帽子、太陽眼鏡、摺疊傘、薄外套','租車／駕照／保險文件','長者常用物品與飲水'];
const faqs=[['自由分頁是什麼？','不是固定行程，而是「臨時想去／想食」的候選庫；按地區分類，到附近才決定。'],['餐廳照片是不是每間店的實拍？','目前卡片加入的是可直接載入的餐廳／食物風格照片；若要每一間都換成該店實拍照，需要逐店核對圖片來源。'],['Day 2 怎樣安排？','上午酒店附近自由活動，中午選早午餐，14:30去LaLaport，19:00看GUNDAM夜間表演，晚餐再從天神／大名選。'],['咖啡豆去哪買？','Nishinaya coffee 在福岡天神／大名；LaLaport附近另有Honey Coffee那珂本店。'],['不想吃原本晚餐怎麼辦？','進入「自由」→選地區→選餐廳；每張卡都有地址與Google Maps按鈕。']];
let state={tab:'itinerary',day:null,region:'全部',query:''};
const regions=['全部','福岡酒店附近','福岡天神／大名','福岡LaLaport附近','福岡市區／博多','鹿兒島市區','霧島','櫻島','知覽／指宿','福岡延伸'];
function maps(n,a){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(n+' '+a)}
function header(){return `<header class="hero"><h1>鹿兒島家族自駕遊</h1><p>2026/09/27 – 10/06 ・ 福岡＋鹿兒島</p><div class="meta"><span class="pill">8人主行程 9/27–10/04</span><span class="pill">福岡自由行 10/04–10/06</span></div></header>`}
function tabs(){return `<nav class="tabs">${[['itinerary','📅','行程'],['free','🎟️','自由'],['check','📋','注意'],['flight','✈️','航班'],['faq','💬','問答']].map(x=>`<button class="tab ${state.tab===x[0]?'active':''}" onclick="setTab('${x[0]}')"><div class="ico">${x[1]}</div><span>${x[2]}</span></button>`).join('')}</nav>`}
function itinerary(){if(state.day){const d=days.find(x=>x.n===state.day);return `<div class="detail-head"><button class="back" onclick="state.day=null;render()">‹</button><div><h2>Day ${d.n}｜${d.title}</h2><div class="date">${d.date} ・ ${d.sub}</div></div></div><div class="timeline">${d.events.map((e,i)=>`<div class="event"><div class="dot">${i+1}</div><div class="event-card"><div class="time">${e[0]}</div><h3>${e[1]}</h3><p>${e[2]||''}</p></div></div>`).join('')}</div>`}return `<div class="notice">行程照原計劃整理；「自由」分頁是臨時想去／想食的選擇庫。點Day卡片查看完整時間軸。</div><div class="day-grid">${days.map(d=>`<article class="day-card" onclick="state.day=${d.n};render()"><div class="day-no"><strong>${d.n}</strong><span>DAY</span></div><div class="day-main"><h3>${d.title}</h3><p>${d.date} ・ ${d.sub}</p></div><div class="arrow">›</div></article>`).join('')}</div>`}
function restaurantCard(r){const [region,cat,name,jp,desc,address,key,web]=r;return `<article class="restaurant"><img class="restaurant-img" src="${img(key)}" alt="${name}" loading="lazy"><div class="restaurant-body"><div class="restaurant-title"><div><h3>${name}</h3><div class="jp">${jp}</div></div><span class="category">${cat}</span></div><p class="desc">${desc}</p><div class="address">📍 ${address}</div><div class="restaurant-actions"><a class="map-btn" href="${maps(name,address)}" target="_blank" rel="noopener">Google Maps</a>${web?`<a class="web-btn" href="${web}" target="_blank" rel="noopener">官方網站</a>`:`<a class="web-btn" href="https://www.google.com/search?q=${encodeURIComponent(name)}" target="_blank" rel="noopener">搜尋店家</a>`}</div></div></article>`}
function free(){const q=state.query.trim().toLowerCase();const rr=restaurants.filter(r=>(state.region==='全部'||r[0]===state.region)&&(!q||r.join(' ').toLowerCase().includes(q)));const ss=spots.filter(s=>(state.region==='全部'||s[0]===state.region)&&(!q||s.join(' ').toLowerCase().includes(q)));return `<div class="notice"><b>🎟️ 自由分頁</b><br>不是固定行程，是「附近臨時想去／想食」的候選庫。按地區選擇，到了附近再決定。</div><input class="faq-search" value="${state.query}" oninput="state.query=this.value;render()" placeholder="搜尋餐廳、咖啡、甜品、景點…"><div class="filter-row">${regions.map(r=>`<button class="filter ${state.region===r?'active':''}" onclick="state.region='${r}';render()">${r}</button>`).join('')}</div>${ss.length?`<div class="section-title"><h2>📍 景點</h2><span class="small">${ss.length}個</span></div><div class="cards">${ss.map(s=>`<div class="spot-card"><img src="${img(s[3])}" alt="${s[1]}" loading="lazy"><div><h4>${s[1]}</h4><p>${s[2]}</p></div></div>`).join('')}</div>`:''}<div class="section-title"><h2>🍴 餐廳／咖啡／甜品</h2><span class="small">${rr.length}個選擇</span></div><div class="cards">${rr.length?rr.map(restaurantCard).join(''):`<div class="empty">找不到符合條件的選擇</div>`}</div>`}
function check(){const saved=JSON.parse(localStorage.getItem('kagoshima-check')||'[]');return `<div class="notice">出門前逐項打勾，狀態會儲存在手機瀏覽器。</div><div class="check-head"><b>✅ 出發前必備</b><b>${saved.length}/${checklist.length}</b></div><div class="checklist">${checklist.map((x,i)=>`<div class="check-item"><input id="c${i}" type="checkbox" ${saved.includes(i)?'checked':''} onchange="toggleCheck(${i},this.checked)"><label for="c${i}" class="${saved.includes(i)?'done':''}">${x}</label></div>`).join('')}</div>`}
function flight(){return `<div class="notice">✈️ 航班頁集中放出發、國內線及返港重點；時間以機票及航空公司最新通知為準。</div><div class="flight"><div class="route"><span>香港／台北 → 福岡</span><b>9/27</b></div><ul><li>6人香港 → 福岡：UO638</li><li>2人台北 → 福岡，18:00抵達</li><li>8人會合後的士前往天神</li></ul></div><div class="flight"><div class="route"><span>福岡 → 鹿兒島</span><b>9/29</b></div><ul><li>博多 → 鹿児島中央：さくら753号</li><li>14:01–15:42，約100分鐘</li><li>抵達後租車</li></ul></div><div class="flight"><div class="route"><span>鹿兒島 → 福岡 → 香港</span><b>10/04</b></div><ul><li>09:30酒店退房 → 約10:00–10:40鹿兒島機場</li><li>12:00鹿兒島 → 福岡</li><li>13:00抵達福岡後轉航廈</li><li>16:15福岡 → 香港；4人返港，餘下4人福岡自由行</li></ul></div>`}
function faq(){return `<input class="faq-search" value="${state.query}" oninput="state.query=this.value;render()" placeholder="搜尋問題…">${faqs.filter(f=>!state.query||f[0].includes(state.query)||f[1].includes(state.query)).map(f=>`<div class="faq"><button onclick="this.nextElementSibling.hidden=!this.nextElementSibling.hidden">${f[0]} <span>＋</span></button><p hidden>${f[1]}</p></div>`).join('')}`}
function render(){document.querySelector('#app').innerHTML=`<div class="app">${header()}<main class="content">${state.tab==='itinerary'?itinerary():state.tab==='free'?free():state.tab==='check'?check():state.tab==='flight'?flight():faq()}</main>${tabs()}</div>`}
function setTab(t){state.tab=t;state.day=null;if(t!=='free'&&t!=='faq')state.query='';render();window.scrollTo(0,0)}
function toggleCheck(i,on){let a=JSON.parse(localStorage.getItem('kagoshima-check')||'[]');a=on?[...new Set([...a,i])]:a.filter(x=>x!==i);localStorage.setItem('kagoshima-check',JSON.stringify(a));render()}
window.setTab=setTab;window.toggleCheck=toggleCheck;window.render=render;window.state=state;render();